"
## Next implementation target 


- Dequeue

May be implementing a queue based on a linked-list and an array can be useful 
in scenario where we do not have OrderedCollection at hand. 

## Done
- Queue
- circular linked list
- Stack
- Double linked list 
- Single linked list
"
Class {
	#name : 'DSRoadmap',
	#superclass : 'Object',
	#category : 'myBecher-DS-Roadmap',
	#package : 'myBecher-DS',
	#tag : 'Roadmap'
}
